name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: denoland/setup-deno@v2
        with:
          deno-version: lts
      - run: deno ci
      - run: deno check
      - run: deno lint
      - run: deno fmt --check
      - run: deno test --allow-run --allow-write --allow-read

  publish:
    # We can omit a test to only run on git tags for now,
    # because "deno publish" checks if we must re-release for us
    # based on the version in the deno file
    name: Deno Publish
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: lts
      - run: deno ci
      - name: Publish vormen package
        run: deno publish
      - name: Publish create-vormen package
        run: cd packages/create-vormen && deno publish
